project:
  type: website
  output-dir: docs
website:
  title: "Ankur Jamwal"
  site-url: https://ankurjamwal.github.io/
  description: "Climate Change-Human-Food nexus"
  open-graph:
    image: images/odl_logo.png
    title: "Ankur Jamwal"
    description: "Climate Change-Human-Food nexus"
  navbar:
    search: true
    left: 
      - text: '<span class="navbar-tagline">Blog: Climate Change X Food Security</span>'
        href: blog.qmd
     

    right: 
      - text: '---'
      - text: 'Academic advising (APU students only)'
        href: https://calendar.app.google/tjACKiReouT5s3MQ8
      - text: "More"
        menu: 
          - text: 'Crosswords'
            href: crosswords.qmd
          - text: 'Bengaluru Gone Thirsty'
            href: https://ankurjamwal.quarto.pub/bengaluru/
          - icon: rss
            href: index.xml
            
      - text: '---'
      
  google-analytics: "G-YEV355G40S"
  page-footer:
    left: "Copyright 2026, Ankur Jamwal"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/ankurjamwal
format:
  html:
    theme:
      light: [flatly, custom.scss]
      dark: [darkly, custom-dark.scss]
    #css: styles.css
    mainfont: "IBM Plex Sans"
    monofont: "IBM Plex Mono"
editor: visual